INSERT NFL.Teams(TeamName, ByeWeek)
VALUES
	(N'Arizona Cardinals', 12),
	(N'Atlanta Falcons', 9),
	(N'Baltimore Ravens', 8),
	(N'Buffalo Bills', 6),
	(N'Carolina Panthers', 7),
	(N'Cincinnati Bengals', 9),
	(N'Chicago Bears', 6),
	(N'Cleveland Browns', 7),
	(N'Dallas Cowboys', 8),
	(N'Denver Broncos', 10),
	(N'Detroit Lions', 5),
	(N'Green Bay Packers', 11),
	(N'Houston Texans', 10),
	(N'Indianapolis Colts', 6),
	(N'Jacksonville Jaguars', 10),
	(N'Kansas City Chiefs', 12),
	(N'Los Angeles Chargers', 12),
	(N'Los Angeles Rams', 9),
	(N'Miami Dolphins', 5),
	(N'Minnesota Vikings', 12),
	(N'New England Patriots', 10),
	(N'New Orleans Saints', 9),
	(N'New York Giants', 11),
	(N'New York Jets', 4),
	(N'Oakland Raiders', 6),
	(N'Philadelphia Eagles', 10),
	(N'Pittsburgh Steelers', 7),
	(N'San Francisco 49ers', 4),
	(N'Seattle Seahawks', 11),
	(N'Tampa Bay Buccaneers', 7),
	(N'Tennessee Titans', 11),
	(N'Washington Redskins', 10)